import sys
import os
from django.utils.safestring import mark_safe
from django.contrib.staticfiles import finders
from django.utils import six
if six.PY2:
    from urlparse import urljoin
elif six.PY3:
    from urllib.parse import urljoin
from .services import WebpackService
from .exceptions import ConfigNotFound, BundlingError
from .settings import BUNDLE_ROOT, BUNDLE_URL, CACHE

webpack_service = WebpackService()

# An in-memory cache of the output generated by the webpack service
cache = {}


def bundle(path_to_config):
    if os.path.isabs(path_to_config):
        if not os.path.exists(path_to_config):
            raise ConfigNotFound(path_to_config)
    else:
        absolute_path_to_config = finders.find(path_to_config)
        if absolute_path_to_config:
            path_to_config = absolute_path_to_config
        else:
            raise ConfigNotFound(path_to_config)

    if not os.path.exists(path_to_config):
        raise ConfigNotFound(path_to_config)

    if CACHE and cache.get(path_to_config, None):
        return cache[path_to_config]

    output = webpack_service.bundle(path_to_config)

    output_path = output['config']['output']['path']

    # Indicate the bundles generated
    assets = []
    for asset in output['stats']['assets']:
        assets.append({
            'name': asset['name'],
            'path': os.path.join(output_path, asset['name'])
        })

    output['assets'] = assets

    if CACHE:
        cache[path_to_config] = output

    return output


class WebpackBundle(object):
    path_to_config = None
    bundle_output = None

    def __init__(self, path_to_config):
        self.path_to_config = path_to_config

    def render(self):
        """
        Returns HTML script elements pointing to the assets generated by webpack
        """
        scripts = []
        # Ensure that all exceptions raise flags, even the ones that django will silently suppress
        try:
            urls = self.get_urls()
        except (TypeError, AttributeError) as e:
            six.reraise(BundlingError, BundlingError(*e.args), sys.exc_info()[2])
        if urls:
            for url in urls:
                scripts.append(
                    '<script src="{url}"></script>'.format(url=url)
                )
            return mark_safe(''.join(scripts))
        return ''

    def get_bundle_output(self):
        if self.bundle_output is None:
            self.bundle_output = bundle(self.path_to_config)
        return self.bundle_output

    def get_urls(self):
        """
        Returns a url to the bundle
        """
        urls = []
        assets = self.get_assets()
        if assets:
            for asset in self.get_assets():
                rel_path = asset['path'].split(BUNDLE_ROOT)[-1]
                if rel_path.startswith('/'):
                    rel_path = rel_path[1:]
                url = urljoin(BUNDLE_URL, rel_path)
                urls.append(url)
            return urls

    def get_assets(self):
        bundle_output = self.get_bundle_output()
        if bundle_output:
            return self.get_bundle_output().get('assets')

    def get_config(self):
        bundle_output = self.get_bundle_output()
        if bundle_output:
            return bundle_output.get('config', None)

    def get_library(self):
        config = self.get_config()
        if config and 'output' in config:
            return config['output'].get('library', None)